### ISSUE TITLE
Item mismatch between this crate and BytesCodec in tokio_io

### ISSUE THREAD

**Issue by aidanhs** [luben/tokio-serde-bincode#5]
The `Encoder` implementation of [BytesCodec](https://docs.rs/tokio-io/0.1.6/tokio_io/codec/struct.BytesCodec.html#impl-Encoder) has `type Item = Bytes`.

This crate has `impl<T, U> Sink for WriteBincode<T, U>` requiring `T: Sink<SinkItem = BytesMut>` - https://github.com/alexcrichton/tokio-serde-bincode/blob/18e783d/src/lib.rs#L170-L173

Altering BytesCodec fixes the issue, but it's not clear at a glance which crate is wrong - maybe this crate should use `Into<BytesMut>` instead, accepting both a `Bytes` and `BytesMut`?

(I've moved on from my attempt to use `BytesCodec` so don't have any vested interest, but thought I'd raise the issue)

**Comment by alexcrichton** [comment]
I don't actually own this name [on crates.io](https://crates.io/crates/tokio-serde-bincode), so this may belong elsewhere perhaps?

**Comment by aidanhs** [comment]
No I am referring to this crate :) I was trying to migrate from the one on crates.io to this repo and hit this issue (along with others)

**Comment by alexcrichton** [comment]
Ah ok, no worries! Unfortunately though I'm not maintaining this crate much any more, so if you'd like me to add you as a collaborator I certainly can!

**Comment by luben** [comment]
I have pushed v0.2.0 that upgrades to tokio-serde-0.3.0 and I think it solves the problem. Can you confirm it solves the issue?

BTW, now it's available from crates.io
